### ISSUE TITLE
missing memory data

### ISSUE THREAD

**Issue by SHITIANYU-hue** [CR-Gjx/Suspicion-Agent#1]
When i try to run: python main_vs_baseline.py --user --verbose_print  --rule_model dqn
<img width="1512" alt="image" src="https://github.com/CR-Gjx/Suspicion-Agent/assets/38762389/59bced53-0333-46b3-baf9-ecec210dc2a2">

It can successfully run few rounds but it will end up with error:
Traceback (most recent call last):
  File "/home/tianyu/code/gameai/Suspicion-Agent/main_vs_baseline.py", line 248, in <module>
    run(args)
  File "/home/tianyu/code/gameai/Suspicion-Agent/main_vs_baseline.py", line 187, in run
    act, comm, bot_short_memory, bot_long_memory = amy.make_act(amy_obs,opponent_name, amy_index,valid_action_list, verbose_print= args.verbose_print,
  File "/home/tianyu/code/gameai/Suspicion-Agent/agent.py", line 449, in make_act
    util.get_logging(logger_name=log_file_name + '_obs',
  File "/home/tianyu/code/gameai/Suspicion-Agent/util.py", line 35, in get_logging
    logHandlerJson = logging.FileHandler('./memory_data/'+logger_name+'.json')
  File "/home/tianyu/anaconda3/envs/rlcard/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/tianyu/anaconda3/envs/rlcard/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: '/home/tianyu/code/gameai/Suspicion-Agent/memory_data/board_game_expert_vs_GoodGuy_dqn_openai-gpt-4-0613_second_tom_obs.json'

**Comment by CR-Gjx** [comment]
Hello, Thanks for your interest! I think creating a folder named 'memory_data' can solve it!
